
CC = g++
path_to = 

cpp_var_test:
	$(CC) -g ./cpp_var/new_work.cpp -lpthread
	./a.out


posix_var_test:
	$(CC) -g ./posix_var/work.cpp -lpthread
	./a.out
	rm a.out

opem_mp_var_test:
	$(CC) -g ./open_mp_var/work.cpp -fopenmp
	./a.out
	rm a.out